### ISSUE TITLE
Chrome: ERROR unknown error: failed to close UI debuggers

### ISSUE THREAD

**Issue by dzharii** [dzharii/swd-recorder#17]
Google Chrome only:
When I am using WebElement Explorer together with Debugger toolbar, the following exception occurs and WEE cannot be started again

> > 2013-09-07 21:39:43.4139 ERROR unknown error: failed to close UI debuggers
> >   (Session info: chrome=29.0.1547.66)
> >   (Driver info: chromedriver=2.3,platform=Windows NT 6.1 SP1 x86_64)

**Comment by kohliHarshit** [comment]
Hi,

Can you please let me know the resolution for this ? I'm facing a similar issue with Chrome v 36 and Chrome Driver v 2.12

Thanks,
Harshit Kohli

**Comment by fancywriter** [comment]
I am facing that too with chromedriver-2.25.

**Comment by serhiiivashchenko** [comment]
Facing with  chromedriver-2.25

`org.openqa.selenium.NoSuchSessionException: no such session
  (Driver info: chromedriver=2.25.426924 (649f9b868f6783ec9de71c123212b908bf3b232e),platform=Linux 3.13.0-101-generic x86_64) (WARNING: The server did not provide any stacktrace information)
Command duration or timeout: 1 milliseconds
Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'
System info: host: 'selenium8.tc.kreditech', ip: '10.200.17.8', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-101-generic', java.version: '1.8.0_111'
Driver info: org.openqa.selenium.chrome.ChromeDriver
Capabilities [{message=session not created exception
from unknown error: failed to close UI debuggers`

Thanks,
Serhii

**Comment by Aaronstein** [comment]
Seems to happen with a lot of sessions ( > 30 ) on a single server.
