### ISSUE TITLE
Add validation for empty values on the Locators form

### ISSUE THREAD

**Issue by dzharii** [dzharii/swd-recorder#28]
Add validation in case of empty form before performing Highlight / Test operation on empty element

Kudos for this finding to Sunny
https://groups.google.com/d/msg/selenium-users/epneoHaOymk/4rS-YHGpt5EJ

Video:
https://www.youtube.com/watch?v=Ajz05OFB7Ps

**Comment by vladimir100** [comment]
Hello Dmytro,
Do you plan to expand your recorder for the Mac OS?
Regards,Vladimir

Date: Mon, 5 Jan 2015 23:19:25 -0800

**Comment by dzharii** [comment]
Hi Vladimir (@vladimir100), 

No, I am not planning porting Page Recorder to MacOS in the nearest future. 
It is written in C#. And... unfortunately, the Webdriver implementation 
and its dependencies is not officially supported on Mono for MacOs and Linux. 

That would require me to rewrite **everything** on Java. 
I am not planning to do that now ;)

- Dima
