### ISSUE TITLE
Browser URL field is disabled

### ISSUE THREAD

**Issue by arulrajj** [dzharii/swd-recorder#33]
Not able to enter the URL in the Browser field as its disabled. Why its disabled ? I had downloaded the latest release [Build#2015.04.14]. Any configuration issues ? 

Can any one suggest workaround or solution for this ?

**Comment by dzharii** [comment]
Hi @arulrajj , 

The field will be disabled until you'll start new browser via Page Recorder. 

![image](https://cloud.githubusercontent.com/assets/36020/7656348/c3e6ce8a-fade-11e4-919a-f9485f032917.png)
