### ISSUE TITLE
Project cannot find the drivers..

### ISSUE THREAD

**Issue by AcousticGuitar** [dzharii/swd-recorder#41]
Hello, thanks for your work on this project, I am interested in it.

I downloaded the project compiled and ran it, it seems to be looking for the drivers.  My question is where do I put the drivers?  In the project of anywhere on the system (and adding to the Path environment statement?)

**Comment by sergueik** [comment]
Hello 

TheOpen QA.Selenium.DriverWerviceNotFoundException  dialog about the missing chromedriver.exe or phantomjs.exe  suggests the url to  download the driver. Have you tried
http://phantomjs.org/download.html  and
https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by AcousticGuitar** [comment]
Thanks for update, I was hoping the project was "ready to go" but will adjust accordingly.
