### ISSUE TITLE
Support for multiple platforms

### ISSUE THREAD

**Issue by email2vimalraj** [dzharii/swd-recorder#45]
Hi,

I like this project. Is there any plan to support other platforms like MacOs, Linux and so on.

**Comment by dzharii** [comment]
Hi @email2vimalraj, 

Not for this project. The biggest challenge now is porting user interface code. For now, I am using Visual Studio which allows me to reduce the time I have to spend on adding new button. In general, Mono supports Windows Forms on Linux and Mac... but the reality is: the UI looks ugly and works really slow (but it works) on  the platforms other than windows. 

The only way is to **rewrite** the project in:
* C++ and QT
* or make a local web-server application and use HTML5 + JavaScript for UI

I am thinking about this for the next project... but not for this one ;)

**Comment by email2vimalraj** [comment]
Thanks for replying @dzharii. Let me know in case you need a contributor for your next project.

**Comment by sergueik** [comment]
Hello Vimal

I has working on the same, (but moved to other areas temporarily) let me know where you stand
Serguei Kouzmine
--------------------------------------------
On Wed, 2/10/16, Vimal Raj <notifications@github.com> wrote:

 Subject: Re: [swd-recorder] Support for multiple platforms (#45)
 To: "dzharii/swd-recorder" <swd-recorder@noreply.github.com>
 Date: Wednesday, February 10, 2016, 12:59 PM
 
 Thanks for replying @dzharii. Let me know
 in case you need a contributor for your next project.
 
 —
 Reply to this email directly or view
 it on GitHub.

**Comment by dzharii** [comment]
@email2vimalraj 
> Let me know in case you need a contributor for your next project.
Roger that! ;)
