### ISSUE TITLE
cannot get absolute xpath like firepath or firebug

### ISSUE THREAD

**Issue by dannydong** [dzharii/swd-recorder#46]
Dear authors, 

This is a great application for web automation, but I am experiencing a problem during my work with it. The swd-recorder captures the xpath which is something like (in the output pox file): 
 <Locator>id("svep_19_i0_508")/div[1]/img[1]</Locator>

However, the id of "svep_19_i0_508" always changes because of the id is generated dynamically by the Web server, so when I re-open the page, I always fail to find the page element recorded.

What I expect is something similar with :"html/body/section/section/x1-workspaces/div/div[2]/x1-tabset/ul/li[7]/a

A work-round is to use the firepath to get the absolute xpath, so I hope the swd-recorder can extract the absolute xpath of page elements, probably it can re-use the interface of firepath or firebug?

Very appreciate with your help.

**Comment by sergueik** [comment]
Hello

It is clearly possible to generate a locator in a format
```
return '//' + elementTagName + '[@id="' + element.id + '"]';
```
rather than 
```
return 'id("' + element.id + '")';
```
 (with possible variations like the one you provided) - the result is simply a string.
Isn't the usage of absolute XPaths discouraged in general ?

**Comment by dzharii** [comment]
Hi @dannydong, 

I have created a patch that might provide a hotfix for this case. 

0. Close Page Recorder
1. Open folder `SwdPageRecorder_v2...\JavaScript\`
2. Rename file `ElementSearch.js` to `Backup_ElementSearch.js`
3. Download, unzip and copy patched `ElementSearch.js` to the folder `SwdPageRecorder_v2...\JavaScript\`


**PATCH ATTACHMENT**
[ElementSearch.zip](https://github.com/dzharii/swd-recorder/files/181143/ElementSearch.zip)

**Comment by dannydong** [comment]
Thank a lot @dzharii and @sergueik, I have done a quick test with the patch, it does work! Very helpful, appreciate with your help. Great!

**Comment by dannydong** [comment]
I will close the issue since it was resolved

**Comment by dzharii** [comment]
@dannydong I am glad it has helped you!
