### ISSUE TITLE
Failed to start up socket due to 'OpenQA.Selenium.WebDriverException'

### ISSUE THREAD

**Issue by nitfeu** [dzharii/swd-recorder#50]
@dzharii 
I am very new to Test automation with Java programming and I wanted to make my work more simple by creating page objects with your tool. But I was unable to run this program from my local machine due to access permissions and so I tried to run it from a shared folder and I got the below message.

![error](https://cloud.githubusercontent.com/assets/26736423/24407091/3499e472-13ca-11e7-94b6-8a3b2288d29b.png)

Kindly let me know if I am missing something or if there are any pre-requisites that I should consider before running the tool.

**Comment by dzharii** [comment]
Hi @nitfeu, could you please try to run it with Google Chrome (and chromedriver)?

**Comment by nitfeu** [comment]
Now I got the below error messages.
![chromedriver_swd_message](https://cloud.githubusercontent.com/assets/26736423/24441001/bc2eb448-1457-11e7-98e4-e41eff861370.png)

**Comment by dzharii** [comment]
Hi @nitfeu, 
Thank you, based on your input, I have decided to upgrade some project dependencies and libraries to the latest version. 

I'm  not sure if the would fix the issue, but could you please give a try to the latest release: 

[https://github.com/dzharii/swd-recorder/releases/tag/v3.3.0-2017.03.29](https://github.com/dzharii/swd-recorder/releases/tag/v3.3.0-2017.03.29)

**Comment by nitfeu** [comment]
Hello @dzharii 
The new updated version works perfectly fine. Thanks for the quick response and update. Kudos to you!!

**Comment by dzharii** [comment]
Sound great. Thank you @nitfeu for your assistance with testing the new release! ;)
